services:
  php:
    build: .
    depends_on:
      - mysql
    ports:
      - 81:80        # ← was 80, nu 81
    volumes:
      - ./src:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "veiligwachtwoord"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - certs:/ssl
      - mysqlconf:/etc/mysql/conf.d/
    ports:
      - 3307:3306    # ← was 3306, nu 3307

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80      # ← was 8080, nu 8081
    environment:
      PMA_HOST: mysql

volumes:
  mysqldata:
  certs:
  mysqlconf: